### PR TITLE
Always merge branchs

### PR DESCRIPTION
**Pull request by RDCH106**
Please, merge the changes and not steal the commits....
Merge development branch with master branch.

I will continue make contributions if the repository contributions are well managed.

### CODE REVIEW

**Comment by RDCH106** [comment]
If you use wrong way to work, it is imposible syncronize mi fork with your project and make contributions. Another reason it is the authority of the commits. If I make the commit with the changes, the commit goes with my signature and not yours. This also important for the trazability of the changes.

**Comment by anfederico** [comment]
I'm not stealing your commits. Push to the master branch. I don't even know why those other branches exist. If you want the contribution for adding the jquery ui tag I'll bring the repository back.

**Comment by RDCH106** [comment]
Ok!

I explain you. This is the main flow to develop in any repository:

workflow.

Usally develop activity is made in develop branch (in your case development). If the amount of changes is significantly large, you can create a feature brach created from develop. When the changes are ready, feature branch is merged with develop and develop with master.

**Master only must contain the merged changes when they are tested and they are considered stable.**

The development branch surely was created automatically if you use gitflow assistant.

And my question now is, how are you pushing the changes from development in master? manually?
If you are not sure about how to merge the changes from development in master, I can do that for you when al the changes are ready and stable. I that moment I send you a PR from my master in my fork to your master en the upstream repository.

**Comment by anfederico** [comment]
Yes, I understand. I don't use multiple branches on simple projects like this when I am the main contributor. I figure if people want to contribute they can just clone the repository, make a change, and then send a pull request to the master.  Shouldn't be an issue.

**Comment by RDCH106** [comment]
It is not a problem if you check the PR before merge it into master.

If you merge directly without test thee changes, develop branch has more sense because the unstable or unexpected behaviour can be fix in the branch and then merge with master branch.

Usually master branch has the most stable state of the project.

**Comment by anfederico** [comment]
Right, I understand, and it's good practice. Just a bit unnecessary for a small project like this. We will stick with one master branch, just merge directly into it, and I will test changes as they come in.

**Pull request merged**
